version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2024.10
    steps:
      - run: echo "Hi I'm on a Container Runner!"
      
  test-java:
    docker:
      - image: cimg/openjdk:17.0

    steps:
      - checkout
      
      - run:
          name: Calculate cache key
          command: |-
            find . -name 'pom.xml' -o -name 'gradlew*' -o -name '*.gradle*' | \
                    sort | xargs cat > /tmp/CIRCLECI_CACHE_KEY

      - restore_cache:
          key: cache-{{ checksum "/tmp/CIRCLECI_CACHE_KEY" }}

      - run:
          name: Run Tests
          command: mvn verify

      # Collect Code Coverage Reports
      - run:
          name: Collect Code Coverage Reports
          command: |
            mkdir -p /tmp/code-coverage
            echo "Finding code coverage reports..."
            find . -type d -name "jacoco" -exec cp -r {} /tmp/code-coverage/ \; || true
            echo "Collected code coverage reports:"
            ls -R /tmp/code-coverage
            
      - store_test_results:
          path: /tmp/code-coverage

      - store_artifacts:
          path: /tmp/code-coverage  # Store the collected code coverag
